# This workflow will:
# - install Python dev dependencies
# - run black, isort, flake8, mypy and pytest

name: Python application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  test-3-11:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: make setup-dev
      - name: Lint with flake8
        run: make flake8
      - name: Run formatters
        run: make format-check
      - name: Typecheck with mypy
        run: make mypy
      - name: Check script
        run: btac --version && btac --help
      - name: Test with pytest
        run: make test

  test-3-8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: make setup-dev
      - name: Check script
        run: btac --version && btac --help
      - name: Test with pytest
        run: make quick-test
